language: c
<<<<<<< .merge_file_iPE3kt
sudo: requried
dist: trusty

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y gettext

install:
    - wget -q https://github.com/racaljk/hosts/releases/download/checkhosts/dos2unix-7.3.4.tar.gz
    - tar xf dos2unix-7.3.4.tar.gz
    - cd dos2unix-7.3.4 && make && sudo make prefix=/usr install
    - cd ..

script:
    # Be permissive, unset following enviroment
    - export STRICT_HOSTS_FORMAT=1
=======
sudo: false
dist: trusty

script:
>>>>>>> .merge_file_E1LSo1
    - bash tools/checkhosts.sh hosts
